# Generated by Django 2.2 on 2020-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200620_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='pt_expel_moeny',
            field=models.FloatField(default=0, verbose_name='抛出金额'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='pt_moeny',
            field=models.FloatField(default=0, verbose_name='赚取金额设定'),
            preserve_default=False,
        ),
    ]
