# Generated by Django 2.2 on 2020-06-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200620_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='pay_type',
            field=models.IntegerField(default=0, verbose_name='交易类型'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='pt_expel_moeny',
            field=models.FloatField(default=0, verbose_name='抛出金额'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='pt_moeny',
            field=models.FloatField(default=0, verbose_name='赚取金额设定'),
        ),
    ]
