# Generated by Django 2.2 on 2020-06-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200620_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='pay_type',
        ),
        migrations.AlterField(
            model_name='pay',
            name='t_pay',
            field=models.DateTimeField(auto_now_add=True, verbose_name='充值时间'),
        ),
    ]
