# Generated by Django 2.2 on 2020-06-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200620_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='u_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
