# Generated by Django 2.2 on 2020-06-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pay_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='share_moeny',
            field=models.FloatField(default=0, verbose_name='推广佣金'),
        ),
    ]
