# Generated by Django 2.2 on 2020-06-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200620_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottery',
            old_name='lottery_moeny',
            new_name='lottery_money',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='pt_expel_moeny',
            new_name='pt_expel_money',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='pt_moeny',
            new_name='pt_money',
        ),
        migrations.RenameField(
            model_name='platformmoney',
            old_name='pt_expel_moeny',
            new_name='pt_expel_money',
        ),
        migrations.RenameField(
            model_name='platformmoney',
            old_name='pt_moeny',
            new_name='pt_money',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='share_moeny',
            new_name='share_money',
        ),
        migrations.RenameField(
            model_name='userbet',
            old_name='bet_moeny',
            new_name='bet_money',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='share_moeny',
            new_name='share_money',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='share_moeny_today',
            new_name='share_money_today',
        ),
    ]
