# Generated by Django 2.2 on 2020-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200620_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='pt_total_money',
            field=models.FloatField(default=0, verbose_name='总金额'),
        ),
    ]
