# Generated by Django 2.2 on 2020-06-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_platform_pt_total_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='lottery_number',
            field=models.CharField(max_length=128, verbose_name='开奖号码'),
        ),
        migrations.AlterField(
            model_name='lotteryhistory',
            name='lottery_number',
            field=models.CharField(max_length=128, verbose_name='开奖号码'),
        ),
    ]
