# Generated by Django 2.2 on 2020-06-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200622_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryhistory',
            name='t_lottery',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开奖时间'),
        ),
    ]
