# Generated by Django 2.2 on 2020-06-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_lottery_t_lottery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='share_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users', verbose_name='推广人姓名'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='bet_num',
            field=models.IntegerField(verbose_name='投注期号'),
        ),
    ]
