# Generated by Django 2.2 on 2020-06-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200623_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='share_money_today',
        ),
        migrations.AlterField(
            model_name='share',
            name='share_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users', verbose_name='推广人'),
        ),
    ]
