# Generated by Django 2.2 on 2020-06-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200623_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='t_bet',
            field=models.DateTimeField(default='2020-06-22 13:45:57', verbose_name='下期开奖时间'),
        ),
    ]
