# Generated by Django 2.2 on 2020-06-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_lottery_t_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='投注用户')),
                ('bet_num', models.IntegerField(verbose_name='投注期号')),
                ('bet_money', models.FloatField(verbose_name='投注金额')),
                ('lottery_number', models.FloatField(verbose_name='开奖号码')),
                ('win_money', models.FloatField(verbose_name='赚取金额')),
            ],
            options={
                'verbose_name': '投注信息',
                'verbose_name_plural': '投注信息',
                'db_table': 'td_betinfo',
            },
        ),
    ]
